apiVersion: apps/v1
kind: Deployment
metadata:
  name: high-concurrency
  labels:
    app: high-concurrency
spec:
  replicas: 1
  selector:
    matchLabels:
      app: high-concurrency
  template:
    metadata:
      labels:
        app: high-concurrency
    spec:
      containers:
      - name: high-concurrency
        image: kylinxiang/java-http:latest
        ports:
        - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: high-concurrency
spec:
  type: NodePort
  selector:
    app: high-concurrency
  ports:
    - name: http
      protocol: http
      port: 8080
      targetPort: 8080
